### ISSUE TITLE
Using serialization for saving and loading

### ISSUE THREAD

**Issue by luetkemj** [NateTheGreatt/bitECS#67] opened 2021-12-27 00:35 UTC
Serializing a world seems to work but deserializing throws the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'Symbol(storeBase)')
at bitecs.v0.3.34.js:472
```
Here's some repro code:

```
import { createWorld, defineSerializer, defineDeserializer } from "bitecs";

let packet;

export const save = (world) => {
  const serialize = defineSerializer(world);
  packet = serialize(world);
};

export const load = () => {
  let newWorld = createWorld();
  const deserialize = defineDeserializer(newWorld);
  deserialize(newWorld, packet);
  return newWorld;
};
```
I don't get an error if I use defineSerializer with same world that I serialized but I'm trying to figure out how that's useful. If I have the world already, there's no reason to deserialize.

Not sure if bug or I'm missing something...

**Comment by NateTheGreatt** [comment] 2021-12-27 17:17
seems like a bug! thanks for reporting, i'll work on a fix ASAP

**Comment by NateTheGreatt** [comment] 2022-02-22 02:03
@luetkemj it seems this error indicates that `newWorld` does not know about a component that `world` knows about. components automatically register with worlds when they are either added to an entity or a query with that component is called on a world. i created an example which reproduces the error:

```js
import { Types, createWorld, defineSerializer, defineDeserializer, defineComponent, registerComponent, addEntity, addComponent } from "../src/index.js"

export const save = (world) => {
  const serialize = defineSerializer(world)
  return serialize(world)
}

export const load = (world, packet) => {
  const deserialize = defineDeserializer(world)
  deserialize(world, packet)
}

const worldA = createWorld()
const worldB = createWorld()

const C = defineComponent({
  x: Types.f32,
  y: Types.f32,
  z: Types.f32,
})

registerComponent(worldA, C)
// uncomment this line and the error goes away
// registerComponent(worldB, C)

const eidA = addEntity(worldA)

addComponent(worldA, C, eidA)

const packet = save(worldA)

load(worldB, packet)
```

because serializers and deserializers need to have the same exact config up-front, using worlds creates a bit of an edge case if those worlds don't know about the same exact components. avoid this error one should explicitly pass in all components to both the serializer and deserializer for now. 

however, i will be introducing a new function to a future release which should make this easier: `getWorldComponents`

i'm now wondering if it's a bad idea to allow a `world` to be passed into a serializer, and instead if something like this should replace that feature:
```js
const serialize = defineSerializer(getWorldComponents(world))
```

what do you think?

**Comment by luetkemj** [comment] 2022-02-22 16:19
> const serialize = defineSerializer(getWorldComponents(world))

That feels a lot more intuitive to me. If there's a legitimate usecase for passing in the world directly that I'm missing, good documentation should make things clear about when to do what.

**Comment by O4epegb** [comment] 2022-06-20 21:54
Would also love to see some in-build solution for that!

So far I've been using this to keep track of all components (to avoid forgetting to register one):

```
const definedComponents: ComponentType<any>[] = [];

const defineComponent: typeof defineComponentBitecs = (schema, size) => {
  const component = defineComponentBitecs(schema, size);
 
  definedComponents.push(component);

  return component;
};

// component definitions with custom `defineComponent`
// ...

export const registerAllComponents = (world: IWorld) => {
  registerComponents(world, definedComponents);
};
```

**Comment by lunarnet76** [comment] 2024-06-06 16:36
Thank you Nate for your code, I didn't realise you code register a component against a world, if I register all components then it works!!!

also, in case anybody needs it, it took me a while how to actually save it to a file

fs.writeFileSync(this.FilePath(saveName), Buffer.from(data));

and to read
this.typedArrayToBuffer(fs.readFileSync(this.FilePath(saveName)));

with
typedArrayToBuffer(array: Uint8Array): ArrayBuffer {
    return array.buffer.slice(array.byteOffset, array.byteLength + array.byteOffset)
}

(I am unsure why it works but it works for me, which is good enough for now!)

**Comment by NateTheGreatt** [comment] 2024-11-24 22:36
https://github.com/NateTheGreatt/bitECS/tree/rc-0-4-0/docs/Serialization.md

**Closed by NateTheGreatt** 2024-11-24 22:36 UTC
Labels: bug
